### PR TITLE
Remove outdated processes

### PR DESCRIPTION
**Pull request by m-mohr**
These are very much outdated (pre-1.0.0) and it seems we should simply remove them to not get into trouble with people using them (already happened). I think the pg parser should be very much independent of any process release/version and instead, people should always provide their own definitions instead.

Would be nice to get tests running before, but I can't get them running right now (due to lack of Python knowledge, I assume). #36

### CODE REVIEW

**Review by SerRichard — APPROVED** [review]

**Comment by clausmichele** [comment]
@m-mohr would it be possible to expose all the available openEO processes listed on https://processes.openeo.org/ as a JSON as the back-ends are doing in the /processes endpoint? If yes, we could let the parser point to this official list of processes as default and this would solve the tests issue.

**Comment by m-mohr** [comment]
Yes, you can use https://processes.openeo.org/processes.json (for latest) and https://processes.openeo.org/<version>/processes.json (for a tagged version) as baseline. The tests could point to this, indeed, but there shouldn't be a default, I think.
Actually, no specific version should be bundled with the PG parser as PG parsing should be agnostic of the versions of the processes. So each implementation should pass the actual list of processes so that the validation actually validates against the actual implementation, not against the openEO-wide specification.

**Comment by clausmichele** [comment]
Totally agree. I think we can merge this and I will try to fix the tests in another PR.

**Review by clausmichele — APPROVED** [review]

**Comment by m-mohr** [comment]
Merged. I would appreciate if you could work on the tests, @clausmichele.

**Pull request merged**
