### PR TITLE
Simplify installation instructions

### PR DESCRIPTION
**Pull request by soxofaan**
- don't require to use miniconda
- drop conda_environment.yml/requirements.txt, just use standard setup.cfg for dependencies

### CODE REVIEW

**Comment by claxn** [comment]
@soxofaan why not keeping both? We currently have set up both so that one can use the conda environment or the setup.cfg independently.
@lforesta what do you think?

**Comment by lforesta** [comment]
@claxn I think we can skip conda in this case, since we anyway use setup.cfg no? But some dependecies (e.g. python-igraph) have disappeared?

**Comment by claxn** [comment]
@lforesta They only disappeared because this PR is working on the master branch. If you both agree on it, I can remove it. But for the sake of developing I would prefer to keep it...

**Comment by soxofaan** [comment]
As far as I understand, openeo-pg-parser-python is intended to be used as a library/dependency of another application, not as a standalone "app".

This is an interesting read on dependency management for both library and application contexts: https://caremad.io/posts/2013/07/setup-vs-requirement/ 
long story short: use setup.py for libraries, requirements.txt for applications.

I would also recommend against specifying the same set of dependencies in multiple sources (setup.cfg, requirements.txt, ...), because you have to always keep them in sync properly, which you will forget :)  We had that situation in our python client and driver projects and it was annoying, We luckily moved most things to setup.py now.

There is practically no reason to maintain a requirements.txt (or equivalent conda) file if all dependencies are already properly listed in setup.py (or setup.cfg), even for development. When you run `pip install -e .`  (so editable/development mode), all necessary dependencies will be installed (so no need for additional `pip install -r requirements.txt` or equivalent), you can even run it again without issue if you add dependencies (or bump version numbers)

**Comment by claxn** [comment]
@soxofaan : I am not so into all the Python Package management stuff, so thanks a lot for the explanations. I never use "requirements.txt" and put every dependency into setup.cfg, but I am used to work with both, conda envs and the setup.py/setup.cfg file for the actual installation. I totally agree with you that it can cause inconsistencies in maintaining the dependencies for both, so I am happy to remove the conda related stuff from the repo.

**Pull request merged**
